services:
  - type: web
    name: TeamTask-Frontend
    runtime: static
    rootDir: team-tasks
    buildCommand: npm install && npm run build --configuration production
    staticPublishPath: dist/team-tasks
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html